[package]
name = "aoc03"
version = "0.1.0"
authors = ["Hrishi Dharam <hdharam@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
serde_scan = "0.3.2"
