[package]
name = "aoc10"
version = "0.1.0"
authors = ["Hrishi Dharam <hdharam@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_scan = "0.3.2"
plotlib = "0.5.1"
